# sudo: required
# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev xvfb
#   - sudo apt-get install -qq libtiff4-dev libjpeg8-dev libfreetype6-dev liblcms1-dev libwebp-dev
#   - sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv python-pip
#   - sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev libreadline-dev
#   - sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev wget curl llvm

language: python
# python:
#   - "3.6"
#   - "3.7"
#   services:
#   - postgres
#   - redis
# env:
#   - DJANGO=2.2 
#   - DB=posgres
# install:
#   - pip install pipenv
#   - pipenv install
   # - pip install -r requirements.txt
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
    - pip install pipenv
    - pipenv install --dev
    # - pip install -r requirements.txt
before_script:
script:
  - pytest